### ISSUE TITLE
Work with Python

### ISSUE THREAD

**Issue by saulshanabrook** [conda-forge/lldb-feedstock#15]
It would be nice if we could use [the Python API](https://lldb.llvm.org/use/python-reference.html#id7) for lldb. However, if I currently try to import lldb in Python, I get an error:

```bash
$ conda create -c conda-forge -n tmp python lldb
$ conda activate tmp
$ python
Python 3.6.10 | packaged by conda-forge | (default, Apr  6 2020, 14:40:13)
[GCC Clang 9.0.1 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import lldb
Fatal Python error: PyThreadState_Get: no current thread

fish: 'env PYTHONPATH=(lldb -P) python' terminated by signal SIGABRT (Abort)
$ ldb -P
/usr/local/Caskroom/miniconda/base/envs/tmp/lib/python3.6/site-packages
```

**Comment by isuruf** [comment]
This feedstock has not been updated in ages. PRs welcome.

**Comment by saulshanabrook** [comment]
> This feedstock has not been updated in ages. PRs welcome.

Cool! I will work on this. Thanks for the quick reply.

**Comment by saulshanabrook** [comment]
@isuruf reading the [LLDB build docs](https://lldb.llvm.org/resources/build.html#code-signing-on-macos):

> The LLVM project is migrating to a single monolithic respository for LLVM and its subprojects. This is the recommended way to build LLDB. Check out the source-tree with git:

Does that mean it would be better to build LLDB in the clangdev or llvmdev along with those? Instead of building it separately?

**Comment by isuruf** [comment]
> Does that mean it would be better to build LLDB in the clangdev or llvmdev along with those? Instead of building it separately?

No. Building out of tree is supported even though the sources are in one repository.
