### ISSUE TITLE
Uploaded lldb packages are out of date.

### ISSUE THREAD

**Issue by arthurp** [conda-forge/lldb-feedstock#27]
The newest uploaded `lldb` package is 10.0.0 (from https://anaconda.org/conda-forge/lldb as of 2021/04/20). This is quite out of date at this point. There are automatic PRs for updates: #22, #23, #25, #26. It would be nice to update the `lldb` package, or provide a bit of documentation on which `lldb` versions are compatible, so I can use `lldb` from a different package manager without fear

**Comment by isuruf** [comment]
All the update PRs are failing. I don't have time to work on it, so PRs are welcome.

**Comment by xhochy** [comment]
We have now builds for 16.0.6
